const fs = require("fs");
const path = require("path");
const initSqlJs = require("sql.js");
const { dataDir } = require("./config");
const { db, usePostgres } = require("./db");

const logDatabasePath = process.env.LOG_DATABASE_PATH || path.join(dataDir, "instance", "vecinosapp_logs.sqlite");
let logDatabase = null;

type AuditFilters = {
  email?: string;
  method?: string;
  statusCode?: string | number;
  path?: string;
  limit?: string | number;
  offset?: string | number;
};

type ApiLogEntry = {
  userId?: number;
  userEmail?: string;
  method: string;
  path: string;
  statusCode: number;
  durationMs: number;
  action?: string;
  message?: string;
  ip?: string;
  userAgent?: string;
};

function saveLogDb() {
  if (!logDatabase) return;
  fs.mkdirSync(path.dirname(logDatabasePath), { recursive: true });
  const tempPath = `${logDatabasePath}.tmp`;
  fs.writeFileSync(tempPath, Buffer.from(logDatabase.export()));
  fs.renameSync(tempPath, logDatabasePath);
}

async function initLogDb() {
  if (usePostgres) {
    await db.exec(`
      CREATE TABLE IF NOT EXISTS api_logs (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id INTEGER, user_email TEXT, method TEXT NOT NULL, path TEXT NOT NULL,
        status_code INTEGER NOT NULL, duration_ms INTEGER NOT NULL, action TEXT, message TEXT,
        ip TEXT, user_agent TEXT, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
      );
      CREATE INDEX IF NOT EXISTS idx_api_logs_created_at ON api_logs(created_at);
      CREATE INDEX IF NOT EXISTS idx_api_logs_user ON api_logs(user_id, created_at);
    `);
    return;
  }
  if (logDatabase) return;
  const SQL = await initSqlJs();
  fs.mkdirSync(path.dirname(logDatabasePath), { recursive: true });
  logDatabase = fs.existsSync(logDatabasePath) && fs.statSync(logDatabasePath).size > 0
    ? new SQL.Database(fs.readFileSync(logDatabasePath))
    : new SQL.Database();
  logDatabase.exec(`
    CREATE TABLE IF NOT EXISTS api_logs (
      id INTEGER PRIMARY KEY AUTOINCREMENT, user_id INTEGER, user_email TEXT,
      method TEXT NOT NULL, path TEXT NOT NULL, status_code INTEGER NOT NULL,
      duration_ms INTEGER NOT NULL, action TEXT, message TEXT, ip TEXT, user_agent TEXT,
      created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
    );
    CREATE INDEX IF NOT EXISTS idx_api_logs_created_at ON api_logs(created_at);
    CREATE INDEX IF NOT EXISTS idx_api_logs_user ON api_logs(user_id, created_at);
  `);
  saveLogDb();
}

function baseAuditWhere() {
  return [
    "method IN ('POST', 'PUT', 'PATCH', 'DELETE')",
    "path NOT LIKE '/css/%'",
    "path NOT LIKE '/js/%'",
    "path NOT LIKE '/favicon/%'",
    "path != '/favicon.ico'",
    "path NOT LIKE '/.well-known/%'"
  ];
}

function auditFilters(filters: AuditFilters = {}) {
  const where = baseAuditWhere();
  const params = [];
  if (filters.email) { where.push("user_email LIKE ?"); params.push(`%${filters.email}%`); }
  if (filters.method) { where.push("method = ?"); params.push(filters.method); }
  if (filters.statusCode) { where.push("status_code = ?"); params.push(filters.statusCode); }
  if (filters.path) { where.push("path LIKE ?"); params.push(`%${filters.path}%`); }
  return { where, params };
}

async function writeApiLog(entry: ApiLogEntry) {
  if (!usePostgres && !logDatabase) return;
  const params = [entry.userId || null, entry.userEmail || null, entry.method, entry.path, entry.statusCode, entry.durationMs, entry.action || null, entry.message || null, entry.ip || null, entry.userAgent || null];
  const sql = `INSERT INTO api_logs (user_id, user_email, method, path, status_code, duration_ms, action, message, ip, user_agent) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`;
  if (usePostgres) return db.prepare(sql).run(...params);
  logDatabase.run(sql, params);
  saveLogDb();
}

async function listApiLogs(filters: AuditFilters = {}) {
  if (!usePostgres && !logDatabase) return [];
  const { where, params } = auditFilters(filters);
  const limit = Math.min(Math.max(Number(filters.limit) || 50, 10), 100);
  const offset = Math.max(Number(filters.offset) || 0, 0);
  const sql = `SELECT id, user_id, user_email, method, path, status_code, duration_ms, action, message, ip, user_agent, created_at FROM api_logs WHERE ${where.join(" AND ")} ORDER BY id DESC LIMIT ? OFFSET ?`;
  if (usePostgres) return db.prepare(sql).all(...params, limit, offset);
  const statement = logDatabase.prepare(sql);
  try {
    statement.bind([...params, limit, offset]);
    const rows = [];
    while (statement.step()) rows.push(statement.getAsObject());
    return rows;
  } finally { statement.free(); }
}

async function countApiLogs(filters: AuditFilters = {}) {
  if (!usePostgres && !logDatabase) return 0;
  const { where, params } = auditFilters(filters);
  if (usePostgres) return Number((await db.prepare(`SELECT COUNT(*) AS total FROM api_logs WHERE ${where.join(" AND ")}`).get(...params)).total || 0);
  const statement = logDatabase.prepare(`SELECT COUNT(*) AS total FROM api_logs WHERE ${where.join(" AND ")}`);
  try {
    if (params.length) statement.bind(params);
    return statement.step() ? Number(statement.getAsObject().total || 0) : 0;
  } finally { statement.free(); }
}

async function apiLogSummary() {
  if (!usePostgres && !logDatabase) return { total: 0, withUser: 0, loginEvents: 0 };
  const sql = `SELECT COUNT(*) AS total, SUM(CASE WHEN user_id IS NOT NULL THEN 1 ELSE 0 END) AS with_user, SUM(CASE WHEN path = '/login' AND method = 'POST' THEN 1 ELSE 0 END) AS login_events FROM api_logs WHERE ${baseAuditWhere().join(" AND ")}`;
  if (usePostgres) {
    const row = await db.prepare(sql).get();
    return { total: Number(row?.total || 0), withUser: Number(row?.with_user || 0), loginEvents: Number(row?.login_events || 0) };
  }
  const result = logDatabase.exec(sql);
  const values = result[0]?.values[0] || [0, 0, 0];
  return { total: Number(values[0] || 0), withUser: Number(values[1] || 0), loginEvents: Number(values[2] || 0) };
}

async function clearApiLogs() {
  if (!usePostgres && !logDatabase) return;
  if (usePostgres) {
    await db.prepare("DELETE FROM api_logs").run();
    return;
  }
  logDatabase.run("DELETE FROM api_logs");
  try { logDatabase.run("DELETE FROM sqlite_sequence WHERE name = 'api_logs'"); } catch { /* Table may be empty. */ }
  saveLogDb();
}

module.exports = { apiLogSummary, clearApiLogs, countApiLogs, initLogDb, listApiLogs, writeApiLog };
